server:
  port: 8090

spring:
  application:
    name: auth-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://localhost:8761/eureka

  datasource:
    username: root
    password: dev@123
    url: jdbc:mysql://localhost:3306/auth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  secret: mySecretKey
  expiration: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/