server:
  port: 8050

spring:
  application:
    name: notification-service
  datasource:
    username: root
    password: dev@123
    url: jdbc:mysql://localhost:3306/notification_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

mailjet:
  api:
    public-key: e675cd1502741adeda4f2d4cbdca36df
    private-key: 142f4dfe25986d9a20d9dca2f1331339

twilio:
  account:
    sid: your_twilio_account_sid
  auth:
    token: your_twilio_auth_token
  from:
    phone: +1234567890

jwt:
  secret: mySecretKey

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka