server:
  port: 8081

spring:
  application:
    name: attendance-service
  datasource:
    username: root
    password: dev@123
    url: jdbc:mysql://localhost:3306/attendance_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  cache:
    jcache:
      config: classpath:ehcache.xml

jwt:
  secret: mySecretKey

auth-service:
  base-url: http://localhost:8080  # Auth Service URL
  endpoints:
    get-jwt: /api/auth/login

employee-service:
  base-url: http://localhost:8080
  endpoints:
    get-employee-by-id: /api/employees/{id}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
