server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Api-Gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"  # Frontend URL
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/departments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: benefits-service
          uri: lb://benefits-service
          predicates:
            - Path=/api/benefits/**
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/api/attendance/**
