server:
  port: 8051

spring:
  application:
    name: Benefits-Service
  datasource:
    url: jdbc:mysql://localhost:3306/benefits_db
    username: root
    password: dev@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySecretKey

auth-service:
  base-url: http://localhost:8080  # Auth Service URL
  endpoints:
    get-jwt: /api/auth/login

employee-service:
  base-url: http://localhost:8080
  endpoints:
    get-employee-by-id: /api/employees/{id}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka