server:
  port: 8089

spring:
  application:
    name: department-service
  datasource:
    username: root
    password: dev@123
    url: jdbc:mysql://localhost:3306/department_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  secret: mySecretKey


employee-service:
  base-url: http://localhost:8080/api/employees
  endpoints:
    get-employee-by-id: /{id}
    get-employees-by-department-id: /department/{departmentId}

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka