server:
  port: 8084

spring:
  application:
    name: Employee-Service
  datasource:
    url: jdbc:mysql://localhost:3306/hrms_db
    username: root
    password: dev@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySecretKey

auth-service:
  base-url: http://localhost:8080/api/users
  endpoints:
    create: "/create-for-employee"

department-service:
  base-url: http://localhost:8080/api/departments
  endpoints:
    get-department-by-id: "/{id}"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka